#!/bin/sh
# First-boot network defaults aligned with Yanw3n/imagebuilder files/.
# Keep LAN on the same subnet the user already uses.

uci -q batch <<-EOF
	set network.lan.ipaddr='172.16.25.1'
	set network.lan.netmask='255.255.255.0'
	set network.lan.delegate='0'
	commit network
	set dropbear.@dropbear[0].enable='1'
	set dropbear.@dropbear[0].PasswordAuth='on'
	set dropbear.@dropbear[0].RootPasswordAuth='on'
	set dropbear.@dropbear[0].Port='22'
	set dropbear.@dropbear[0].Interface='lan'
	commit dropbear
EOF

/etc/init.d/network restart
/etc/init.d/dropbear restart

exit 0
